;SAGE I. HENDRICKS 2023 OCT 26
;PLAYING AROUND WITH THE PROM'S VIDEO DRIVER FOR THE NS-ADV
;PRINT HELLORLD (CLOSE) TO THE CENTER OF THE SCREEN

;MADE TO RUN ON THE NORTHSTAR ADVANTAGE

;CONSTANTS
VID0    EQU     1000$0000B      ;VIDEO PART 1 (16K)
VID1    EQU     1000$0001B      ;VIDEO PART 2 (4X 4K)
PROM    EQU     1000$0100B      ;PROM (2K)
PAGE0   EQU     0A0H            ;00000-03FFFH
PAGE1   EQU     0A1H            ;04000-07FFFH
PAGE2   EQU     0A2H            ;08000-0BFFFH
PAGE3   EQU     0A3H            ;0C000-0FFFFH

SCANREG EQU     090H            ;VIDEO SCAN REG. TOP VISIBLE LINE

VBASE   EQU     08000H          ;BASE ADDR OF VIDEO DRIVER
VDRIVER EQU     VBASE+007FDH    ;VIDEO DRIVER JMP ADDR
VFONT   EQU     VBASE+00561H    ;STANDARD CHARACTER SET

NULL    EQU     000H            ;NULL BYTE

CCLEAR  EQU     00FH            ;CLEAR SCREEN CHARACTER
CHOME   EQU     01EH            ;CURSOR HOME CHARACTER
CCURON  EQU     018H            ;CURSOR ON CHARACTER
CCUROFF EQU     019H            ;CURSOR OFF CHARACTER

;CP/M START (VVV LARGE EXECUTABLE)
        ORG     00100H          ;CP/M'S TPA
        JP      START

;PROM START (MUST BE ON SIDE 0 TRACK 0 SECT 4-7 OF FLOPPY)
        ORG     0C000H          ;PROM WILL PUT PROGRAM HERE 
        DB      0C0H            ;FIRST BYTE TELLS THE PROM WHERE THE PROGRAM
                                ;SHOULD BE LOADED, IN MEM. C0 == C0000
        ORG     0C00AH          ;PROM STARTS EXECUTING CODE 10 BYTES AFTER
        JP      START           ;THE SPECIFIED LOAD ADDR, IT EXPECTS A JUMP

;PROGRAM START
START:  
        CALL    MAPMEM          ;MAP THE PROM AND VIEDO MEM TO PROPPER PAGES
        
        CALL    CUROFF          ;TURN THE CURSOR OFF
        CALL    HOME0           ;UNSCROLL, MOVE TO TOP OF DISPLAY RAM
        CALL    HOME1           ;MOVE CURSOR TO HOME POS ON SCREEN
        CALL    CLEAR           ;CLEAR FROM CURSOR TO END OF SCREEN

        LD      A,35            ;MAGIC NUMBER (CENTERS TEXT ON SCREEN)
        CALL    SETCX           ;SET CURSOR X POS
        LD      A,110           ;MAGIC NUMBER 2 ELECTRIC BOOGALOO!
        CALL    SETCY           ;SET CURSOR Y POS

        LD      DE,MSG          ;LOAD MESSAGE ADDR INTO DE
        CALL    PRINT           ;PRINT LOADED MESSAGE FROM CURSOR POS

        HLT                     ;HALT THE SYSTEM

MAPMEM: LD      A,VID0          ;SPECIFY VRAM PART 1
        OUT     (PAGE0),A       ;MAP TO PAGE 0
        LD      A,VID1          ;SPECIFY VRAM PART 2
        OUT     (PAGE1),A       ;MAP TO PAGE 1
        LD      A,PROM          ;SPECIFY PROM (W/ VIDEO DRIVER)
        OUT     (PAGE2),A       ;MAP TO PAGE 2
        RET

COUT:   LD      IX,VBLOCK
        JP      VDRIVER         ;GOTO VDRIVER
RETURN: RET                     ;VDRIVER RETURNS HERE

HOME0:  LD      A,000H          ;SPECIFY TOP OF VRAM
        OUT     (SCANREG),A     ;SET TOP LINE OFFSET TO 00
        RET

HOME1:  LD      A,CHOME         ;LOAD HOME CHARACTER
        CALL    COUT            ;GOTO THE HOME POSITION
        RET

CLEAR:  LD      A,CCLEAR        ;LOAD CLEAR CHARACTER
        CALL    COUT            ;CLEAR FROM CURSOR TO END OF SCREEN
        RET

CURON:  LD      A,CCURON        ;LOAD CURSOR ON CHARACTER
        CALL    COUT            ;TURN THE CURSOR ON
        RET

CUROFF: LD      A,CCUROFF       ;LOAD CURSOR OFF CHARACTER
        CALL    COUT            ;TURN THE CURSOR OFF
        RET

SETCX:  LD      (CURSX),A       ;SET CURSOR X POS TO A
        RET

SETCY:  LD      (CURSY),A       ;SET CURSOR Y POS TO A
        RET

PRINT:  LD      A,(DE)          ;LOAD CHARACTER FROM DE
        CP      NULL            ;CHECK FOR NULL CHARACTER
        RET     Z               ;IF NULL TERMINATOR IS REACHED, RETURN
        PUSH    DE              ;SAVE DE
        CALL    COUT            ;PRINT THE CHARACTER
        POP     DE              ;RESTORE DE
        INC     DE              ;MOVE TO NEXT CHARACTER
        JP      PRINT           ;REPEAT

;DATA BLOCK
;VIDEO DRIVER DATA
VCUR:   DW      0FFFFH,0FFFFH,0FFFFH,0FFFFH,0FFFFH

VBLCOK:
CURSX:  DB      000H            ;CURSOR X POS
CURSY:  DB      000H            ;CURSOR Y POS
PIXEL:  DW      VFONT           ;USE THE STANDARD CHARACTER SET
SCRCT:  DB      000H            ;TOP LINE OFFSET
STATS:  DB      0000$0110B      ;NO-WRAP, NO-SCROLL
RETFP:  DW      RETURN          ;VDRIVER JUMPS HERE AFTER DONE
CTEMP:  DW      VCUR            ;CURSOR TO USE
VMODE:  DB      000H            ;DISPLAY MODE, 00 NORMAL, FF REVERSE

;MESSAGE
MSG:    DB      'HELLORLD',NULL

        END
